spring.application.name=estetica-automotiva
server.port=8080

# Configure com a connection string do MongoDB Atlas.
# Exemplo:
# spring.data.mongodb.uri=mongodb+srv://usuario:senha@cluster.mongodb.net/estetica_automotiva?retryWrites=true&w=majority
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/estetica_automotiva}

spring.thymeleaf.cache=false
server.error.include-message=always
